DROP DATABASE IF EXISTS REPASOINICIAL2;
USE REPASOINICIAL2;

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS NOT NULL,
    PROVINCIA VARCHAR(20) DEFAULT "Murcia",
    COD_POSTAL INT,
    TFNO CHAR(9),
    FECHA_NAC DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI_CLIENTE)
);

DROP TABLE IF EXISTS COCHES;
CREATE TABLE COCHES(
    MATRICULA CHAR(7) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    MODELO VARCHAR(20) NOT NULL,
    COLOR VARCHAR(10) DEFAULT "Negro",
    NUM_CABALLOS INT DEFAULT 90,
    NUM_PUERTAS INT DEFAULT 5,
    CODIGO_CLIENTE INT,
    CONSTRAINT PK_COCHES PRIMARY KEY(MATRICULA),
    CONSTRAINT FK_COCHES_CODIGO_CLIENTE FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTES(DNI) ON DELETE CASCADE
);

DROP TABLE IF EXISTS REVISIONES;
CREATE TABLE REVISIONES(
    CODIGO INT NOT NULL,
    PRECIO FLOAT NOT NULL,
    CODIGO_COCHE INT NOT NULL,
    CONSTRAINT PK_REVISIONES PRIMARY KEY(CODIGO)
);

/*Ejercicio 9*/
DROP TABLE IF EXISTS MEDICOS;
CREATE TABLE MEDICOS(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    ESPECIALIDAD VARCHAR(20) DEFAULT "Psiquitría",
    CONSTRAINT PK_MEDICOS PRIMARY KEY(DNI)
);

DROP TABLE IF EXISTS PACIENTE;
CREATE TABLE PACIENTE(
    DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    PROVINCIA VARCHAR(30) DEFAULT "Murcia",
    COD_POSTAL CHAR(5),
    TFNO CHAR(9),
    FECHA_NAC DATE NOT NULL,
    CONSTRAINT PK_MEDICOS PRIMARY KEY(DNI)
); 

DROP TABLE IF EXISTS INGRESOS;
CREATE TABLE INGRESOS(
    CODIGO_MEDICO CHAR(9) NOT NULL,
    DNI_PACIENTE CHAR(9) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    CONSTRAINT PK_INGRESOS PRIMARY KEY(CODIGO_MEDICO, DNI_PACIENTE),
    CONSTRAINT FK_INGRESOS_CODIGO_MEDICO FOREIGN KEY(CODIGO_MEDICO) REFERENCES MEDICOS(DNI) ON DELETE CASCADE,
    CONSTRAINT FK_INGRESOS_DNI_PACIENTE FOREIGN KEY(DNI_PACIENTE) REFERENCES PACIENTE(DNI) ON DELETE CASCADE
);
